# Writes <engine/build_id.h> with kBuildId and kBuildIdCStr. Run as a build step from CMakeLists.txt:
#   cmake -DINCLUDE_DIR=... -DOUT=... -DSTAMP=... -DCOMPILER=... -DCONFIG=... -DDEFINES=a|b|c -P build_id.cmake
# The id is a hash over every public header (path relative to INCLUDE_DIR plus content, sorted by
# path), the compiler id and version, the configuration, and the engine's PUBLIC compile definitions.
# A game module bakes kBuildId; the editor compares it with engine::build_id() from engine.dll.
# OUT is rewritten only when its content changes, so an unchanged id does not recompile anything.
# STAMP is always touched: it is the custom command's output and keeps the step up to date.

foreach(_var INCLUDE_DIR OUT STAMP COMPILER CONFIG)
    if(NOT DEFINED ${_var})
        message(FATAL_ERROR "build_id.cmake: -D${_var}=... is required")
    endif()
endforeach()

file(GLOB_RECURSE _headers RELATIVE "${INCLUDE_DIR}"
    "${INCLUDE_DIR}/*.h"
    "${INCLUDE_DIR}/*.hpp"
    "${INCLUDE_DIR}/*.inl")
list(SORT _headers)

set(_input "compiler=${COMPILER}\nconfig=${CONFIG}\n")

string(REPLACE "|" ";" _defines "${DEFINES}")
list(REMOVE_ITEM _defines "")
list(REMOVE_DUPLICATES _defines)
list(SORT _defines)
foreach(_define IN LISTS _defines)
    string(APPEND _input "define=${_define}\n")
endforeach()

foreach(_header IN LISTS _headers)
    file(SHA256 "${INCLUDE_DIR}/${_header}" _hash)
    string(APPEND _input "header=${_header}:${_hash}\n")
endforeach()

string(SHA256 _id "${_input}")
string(SUBSTRING "${_id}" 0 16 _id)

set(_content "#pragma once

// Generated by cmake/build_id.cmake. Do not edit. docs/tech/build/CMake.md

#include <string_view>

namespace engine {

// Hash of the public headers, compiler, configuration (${CONFIG}), and PUBLIC engine defines.
// kBuildIdCStr is the null-terminated literal a game module returns from wind_game_build_id.
inline constexpr char kBuildIdCStr[] = \"${_id}\";
inline constexpr std::string_view kBuildId = kBuildIdCStr;

}
")

set(_old "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" _old)
endif()
if(NOT _old STREQUAL _content)
    file(WRITE "${OUT}" "${_content}")
endif()
file(TOUCH "${STAMP}")
