# Writes <prefix>/sdk.toml at the end of `cmake --install` of the editor build. Included from the install script
# generated by CMakeLists.txt, which sets:
#   WIND_SDK_SOURCE_DIR       the engine checkout the SDK was built from
#   WIND_SDK_VERSION          project(engine VERSION)
#   WIND_SDK_CONFIG           the installed configuration
#   WIND_SDK_BUILD_ID_HEADER  that configuration's generated <engine/build_id.h>
# sdk.toml is how the launcher and the editor know an SDK. Keys are only ever added. docs/tech/build/CMake.md

foreach(_var WIND_SDK_SOURCE_DIR WIND_SDK_VERSION WIND_SDK_CONFIG WIND_SDK_BUILD_ID_HEADER)
    if(NOT DEFINED ${_var})
        message(FATAL_ERROR "sdk_manifest.cmake: ${_var} is not set")
    endif()
endforeach()

file(STRINGS "${WIND_SDK_BUILD_ID_HEADER}" _line REGEX "kBuildIdCStr\[\] = \"[0-9a-f]+\"")
if(NOT _line MATCHES "\"([0-9a-f]+)\"")
    message(FATAL_ERROR "sdk.toml: no kBuildIdCStr in ${WIND_SDK_BUILD_ID_HEADER}")
endif()
set(_build_id "${CMAKE_MATCH_1}")

# The commit and whether the checkout had changes (tracked or untracked) when it was installed. An SDK with
# dirty = true is not the build of its version's tag.
find_program(_git git)
if(NOT _git)
    message(FATAL_ERROR "sdk.toml records the engine commit: git was not found")
endif()
execute_process(COMMAND "${_git}" -C "${WIND_SDK_SOURCE_DIR}" rev-parse HEAD
    OUTPUT_VARIABLE _commit OUTPUT_STRIP_TRAILING_WHITESPACE
    RESULT_VARIABLE _result)
if(NOT _result EQUAL 0)
    message(FATAL_ERROR "sdk.toml: git rev-parse HEAD failed in ${WIND_SDK_SOURCE_DIR}")
endif()
execute_process(COMMAND "${_git}" -C "${WIND_SDK_SOURCE_DIR}" status --porcelain
    OUTPUT_VARIABLE _status OUTPUT_STRIP_TRAILING_WHITESPACE
    RESULT_VARIABLE _result)
if(NOT _result EQUAL 0)
    message(FATAL_ERROR "sdk.toml: git status failed in ${WIND_SDK_SOURCE_DIR}")
endif()
if(_status STREQUAL "")
    set(_dirty false)
else()
    set(_dirty true)
endif()

set(_out "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/sdk.toml")
message(STATUS "Installing: ${_out}")
file(WRITE "${_out}" "# Wind editor SDK. Written by cmake --install. Do not edit.
version = \"${WIND_SDK_VERSION}\"
commit = \"${_commit}\"
dirty = ${_dirty}
config = \"${WIND_SDK_CONFIG}\"
build_id = \"${_build_id}\"
")
